---
format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, notebooks/custom.scss]
    output-file: index.html
code-block-background: true

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="index_files/md-default0.js" type="text/javascript"></script><script src="index_files/md-default1.js" type="text/javascript"></script>

# CFD Python in Clojure

We attempt to convert Python written [12 steps of Navier-Stokes learning modules](https://github.com/barbagroup/CFDPython)
into Clojure. By doing so, the objectives are:
1. going through the steps to learn Computational Fluid Dynamics(CFD) in general
2. convert Python written functions into Clojure, so we could further evolve it to
  make it use-able in related science research in the future

## Navier-Stokes equations

Navier-Stokes equations basically describes the movement of viscous fluids using
partial differential equations(PDE).

In general, the equations explains who fluids reacts around given environment,
with states of its density, pressure and temperature.

## Steps


* [Step 1 - 1-D Linear Convection](steps.step_01.html)

* [Step 2 - Nonlinear Convection](steps.step_02.html)

* [Convergence and the CFL Condition](steps.cfl_condition.html)

* [Step 3 - 1-D Diffusion Equation](steps.step_03.html)

* [Step 4 - 1-D Burgers' Equation](steps.step_04.html)

* [Step 5 - 2-D Linear Convection Equation](steps.step_05.html)

* [Step 6 - 2-D Nonlinear Convection Equation](steps.step_06.html)

* [Step 7 - 2-D Diffusion Equation](steps.step_07.html)

* [Step 8 - 2-D Burgers' Equation](steps.step_08.html)

* [Step 9 - Laplace Equation](steps.step_09.html)

* [Step 10 - Poisson Equation](steps.step_10.html)

* [Step 11 - Cavity Flow with Navier-Stokes](steps.step_11.html)

* [Step 12 - Channel Flow with Navier-Stokes](steps.step_12.html)


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/scicloj/cfd-python-in-clojure/blob/main/notebooks/index.clj">notebooks/index.clj</a></small></small></pre></div>
```
