---
format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, notebooks/custom.scss]
    output-file: steps.cfl_condition.html
code-block-background: true

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="steps.cfl_condition_files/md-default0.js" type="text/javascript"></script><script src="steps.cfl_condition_files/md-default1.js" type="text/javascript"></script><script src="steps.cfl_condition_files/vega2.js" type="text/javascript"></script><script src="steps.cfl_condition_files/vega3.js" type="text/javascript"></script><script src="steps.cfl_condition_files/vega4.js" type="text/javascript"></script><script src="steps.cfl_condition_files/katex5.js" type="text/javascript"></script><link href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css" rel="stylesheet" type="text/css" />

# Convergence and the CFL Condition

initial and boundary conditions:



::: {.sourceClojure}
```clojure
(def init-params {:x-start 0
                  :x-end   2
                  :nx      41
                  :nt      20
                  :c       1.0
                  :dt      0.025})
```
:::


41 points of grid and 0.025 sec of timestep.

Experimenting increasing the size of the grid below to see what happens:


$nx = 41$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.05},{"y":1.0,"x":0.1},{"y":1.0,"x":0.15},{"y":1.0,"x":0.2},{"y":1.0,"x":0.25},{"y":1.0,"x":0.3},{"y":1.0,"x":0.35},{"y":1.0,"x":0.4},{"y":1.0,"x":0.45},{"y":1.000001,"x":0.5},{"y":1.00002,"x":0.55},{"y":1.0002012,"x":0.6},{"y":1.0012884,"x":0.65},{"y":1.005909,"x":0.7},{"y":1.0206947,"x":0.75},{"y":1.0576591,"x":0.8},{"y":1.131588,"x":0.85},{"y":1.2517223,"x":0.9},{"y":1.4119015,"x":0.95},{"y":1.5880985,"x":1.0},{"y":1.7482767,"x":1.05},{"y":1.868392,"x":1.1},{"y":1.9421396,"x":1.15},{"y":1.9780169,"x":1.2},{"y":1.9881821,"x":1.25},{"y":1.9780169,"x":1.3},{"y":1.9421396,"x":1.35},{"y":1.868392,"x":1.4},{"y":1.7482767,"x":1.45},{"y":1.5880985,"x":1.5},{"y":1.4119015,"x":1.55},{"y":1.2517223,"x":1.6},{"y":1.131588,"x":1.65},{"y":1.0576591,"x":1.7},{"y":1.0206947,"x":1.75},{"y":1.005909,"x":1.8},{"y":1.0012884,"x":1.85},{"y":1.0002012,"x":1.9},{"y":1.00002,"x":1.95},{"y":1.0000019,"x":2.0}]}});</script></div>
```


$nx = 61$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.033333335},{"y":1.0,"x":0.06666667},{"y":1.0,"x":0.1},{"y":1.0,"x":0.13333334},{"y":1.0,"x":0.16666667},{"y":1.0,"x":0.2},{"y":1.0,"x":0.23333333},{"y":1.0,"x":0.26666668},{"y":1.0,"x":0.3},{"y":1.0,"x":0.33333334},{"y":1.0,"x":0.36666667},{"y":1.0,"x":0.4},{"y":1.0,"x":0.43333334},{"y":1.0,"x":0.46666667},{"y":1.0,"x":0.5},{"y":1.0,"x":0.53333336},{"y":1.0,"x":0.56666666},{"y":1.0,"x":0.6},{"y":1.0000002,"x":0.6333333},{"y":1.0000038,"x":0.6666667},{"y":1.0000294,"x":0.7},{"y":1.0001837,"x":0.73333335},{"y":1.0009356,"x":0.76666665},{"y":1.0039423,"x":0.8},{"y":1.0138645,"x":0.8333333},{"y":1.0409251,"x":0.8666667},{"y":1.1018119,"x":0.9},{"y":1.2142179,"x":0.93333334},{"y":1.3828273,"x":0.96666664},{"y":1.5851585,"x":1.0},{"y":1.7748439,"x":1.0333333},{"y":1.9087396,"x":1.0666667},{"y":1.9756874,"x":1.1},{"y":1.9968288,"x":1.1333333},{"y":1.9999998,"x":1.1666666},{"y":1.9999962,"x":1.2},{"y":1.9999706,"x":1.2333333},{"y":1.9998163,"x":1.2666667},{"y":1.9990644,"x":1.3},{"y":1.9960577,"x":1.3333334},{"y":1.9861355,"x":1.3666667},{"y":1.9590749,"x":1.4},{"y":1.8981881,"x":1.4333333},{"y":1.7857821,"x":1.4666667},{"y":1.6171727,"x":1.5},{"y":1.4148415,"x":1.5333333},{"y":1.2251561,"x":1.5666667},{"y":1.0912604,"x":1.6},{"y":1.0243126,"x":1.6333333},{"y":1.0031712,"x":1.6666666},{"y":1.0,"x":1.7},{"y":1.0,"x":1.7333333},{"y":1.0,"x":1.7666667},{"y":1.0,"x":1.8},{"y":1.0,"x":1.8333334},{"y":1.0,"x":1.8666667},{"y":1.0,"x":1.9},{"y":1.0,"x":1.9333333},{"y":1.0,"x":1.9666667},{"y":1.0,"x":2.0}]}});</script></div>
```


$nx = 81$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.025},{"y":1.0,"x":0.05},{"y":1.0,"x":0.075},{"y":1.0,"x":0.1},{"y":1.0,"x":0.125},{"y":1.0,"x":0.15},{"y":1.0,"x":0.175},{"y":1.0,"x":0.2},{"y":1.0,"x":0.225},{"y":1.0,"x":0.25},{"y":1.0,"x":0.275},{"y":1.0,"x":0.3},{"y":1.0,"x":0.325},{"y":1.0,"x":0.35},{"y":1.0,"x":0.375},{"y":1.0,"x":0.4},{"y":1.0,"x":0.425},{"y":1.0,"x":0.45},{"y":1.0,"x":0.475},{"y":1.0,"x":0.5},{"y":1.0,"x":0.525},{"y":1.0,"x":0.55},{"y":1.0,"x":0.575},{"y":1.0,"x":0.6},{"y":1.0,"x":0.625},{"y":1.0,"x":0.65},{"y":1.0,"x":0.675},{"y":1.0,"x":0.7},{"y":1.0,"x":0.725},{"y":1.0,"x":0.75},{"y":1.0,"x":0.775},{"y":1.0,"x":0.8},{"y":1.0,"x":0.825},{"y":1.0,"x":0.85},{"y":1.0,"x":0.875},{"y":1.0,"x":0.9},{"y":1.0,"x":0.925},{"y":1.0,"x":0.95},{"y":1.0,"x":0.975},{"y":2.0,"x":1.0},{"y":2.0,"x":1.025},{"y":2.0,"x":1.05},{"y":2.0,"x":1.075},{"y":2.0,"x":1.1},{"y":2.0,"x":1.125},{"y":2.0,"x":1.15},{"y":2.0,"x":1.175},{"y":2.0,"x":1.2},{"y":2.0,"x":1.225},{"y":2.0,"x":1.25},{"y":2.0,"x":1.275},{"y":2.0,"x":1.3},{"y":2.0,"x":1.325},{"y":2.0,"x":1.35},{"y":2.0,"x":1.375},{"y":2.0,"x":1.4},{"y":2.0,"x":1.425},{"y":2.0,"x":1.45},{"y":2.0,"x":1.475},{"y":2.0,"x":1.5},{"y":1.0,"x":1.525},{"y":1.0,"x":1.55},{"y":1.0,"x":1.575},{"y":1.0,"x":1.6},{"y":1.0,"x":1.625},{"y":1.0,"x":1.65},{"y":1.0,"x":1.675},{"y":1.0,"x":1.7},{"y":1.0,"x":1.725},{"y":1.0,"x":1.75},{"y":1.0,"x":1.775},{"y":1.0,"x":1.8},{"y":1.0,"x":1.825},{"y":1.0,"x":1.85},{"y":1.0,"x":1.875},{"y":1.0,"x":1.9},{"y":1.0,"x":1.925},{"y":1.0,"x":1.95},{"y":1.0,"x":1.975},{"y":1.0,"x":2.0}]}});</script></div>
```



## Reasons for the breakage

increasing grid size means travelling distance within a $\Delta t$ becomes grater than
$\Delta x$, which correlates to $nx$. In order to enforce the stability, we introduce
**Courant number** $\sigma_{max}$. This ensures stability with given discretization params.


$$\sigma = \frac{u \Delta t}{\Delta x} \le \sigma_{max}$$




::: {.sourceClojure}
```clojure
(def init-params' {:x-start 0
                   :x-end   2
                   :nx      41
                   :nt      20
                   :c       1.0
                   :sigma   0.5})
```
:::


$nx = 41$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.05},{"y":1.0,"x":0.1},{"y":1.0,"x":0.15},{"y":1.0,"x":0.2},{"y":1.0,"x":0.25},{"y":1.0,"x":0.3},{"y":1.0,"x":0.35},{"y":1.0,"x":0.4},{"y":1.0,"x":0.45},{"y":1.000001,"x":0.5},{"y":1.00002,"x":0.55},{"y":1.0002012,"x":0.6},{"y":1.0012884,"x":0.65},{"y":1.005909,"x":0.7},{"y":1.0206947,"x":0.75},{"y":1.0576591,"x":0.8},{"y":1.131588,"x":0.85},{"y":1.2517223,"x":0.9},{"y":1.4119015,"x":0.95},{"y":1.5880985,"x":1.0},{"y":1.7482767,"x":1.05},{"y":1.868392,"x":1.1},{"y":1.9421396,"x":1.15},{"y":1.9780169,"x":1.2},{"y":1.9881821,"x":1.25},{"y":1.9780169,"x":1.3},{"y":1.9421396,"x":1.35},{"y":1.868392,"x":1.4},{"y":1.7482767,"x":1.45},{"y":1.5880985,"x":1.5},{"y":1.4119015,"x":1.55},{"y":1.2517223,"x":1.6},{"y":1.131588,"x":1.65},{"y":1.0576591,"x":1.7},{"y":1.0206947,"x":1.75},{"y":1.005909,"x":1.8},{"y":1.0012884,"x":1.85},{"y":1.0002012,"x":1.9},{"y":1.00002,"x":1.95},{"y":1.0000019,"x":2.0}]}});</script></div>
```


$nx = 61$



```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.033333335},{"y":1.0,"x":0.06666667},{"y":1.0,"x":0.1},{"y":1.0,"x":0.13333334},{"y":1.0,"x":0.16666667},{"y":1.0,"x":0.2},{"y":1.0,"x":0.23333333},{"y":1.0,"x":0.26666668},{"y":1.0,"x":0.3},{"y":1.0,"x":0.33333334},{"y":1.0,"x":0.36666667},{"y":1.0,"x":0.4},{"y":1.0,"x":0.43333334},{"y":1.0,"x":0.46666667},{"y":1.000001,"x":0.5},{"y":1.00002,"x":0.53333336},{"y":1.0002012,"x":0.56666666},{"y":1.0012884,"x":0.6},{"y":1.005909,"x":0.6333333},{"y":1.0206947,"x":0.6666667},{"y":1.0576591,"x":0.7},{"y":1.131588,"x":0.73333335},{"y":1.2517223,"x":0.76666665},{"y":1.4119015,"x":0.8},{"y":1.5880985,"x":0.8333333},{"y":1.7482777,"x":0.8666667},{"y":1.868412,"x":0.9},{"y":1.9423409,"x":0.93333334},{"y":1.9793053,"x":0.96666664},{"y":1.994091,"x":1.0},{"y":1.9987106,"x":1.0333333},{"y":1.9997787,"x":1.0666667},{"y":1.9997787,"x":1.1},{"y":1.9987106,"x":1.1333333},{"y":1.994091,"x":1.1666666},{"y":1.9793053,"x":1.2},{"y":1.9423409,"x":1.2333333},{"y":1.868412,"x":1.2666667},{"y":1.7482777,"x":1.3},{"y":1.5880985,"x":1.3333334},{"y":1.4119015,"x":1.3666667},{"y":1.2517223,"x":1.4},{"y":1.131588,"x":1.4333333},{"y":1.0576591,"x":1.4666667},{"y":1.0206947,"x":1.5},{"y":1.005909,"x":1.5333333},{"y":1.0012884,"x":1.5666667},{"y":1.0002012,"x":1.6},{"y":1.00002,"x":1.6333333},{"y":1.000001,"x":1.6666666},{"y":1.0,"x":1.7},{"y":1.0,"x":1.7333333},{"y":1.0,"x":1.7666667},{"y":1.0,"x":1.8},{"y":1.0,"x":1.8333334},{"y":1.0,"x":1.8666667},{"y":1.0,"x":1.9},{"y":1.0,"x":1.9333333},{"y":1.0,"x":1.9666667},{"y":1.0,"x":2.0}]}});</script></div>
```


$nx = 81$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.025},{"y":1.0,"x":0.05},{"y":1.0,"x":0.075},{"y":1.0,"x":0.1},{"y":1.0,"x":0.125},{"y":1.0,"x":0.15},{"y":1.0,"x":0.175},{"y":1.0,"x":0.2},{"y":1.0,"x":0.225},{"y":1.0,"x":0.25},{"y":1.0,"x":0.275},{"y":1.0,"x":0.3},{"y":1.0,"x":0.325},{"y":1.0,"x":0.35},{"y":1.0,"x":0.375},{"y":1.0,"x":0.4},{"y":1.0,"x":0.425},{"y":1.0,"x":0.45},{"y":1.0,"x":0.475},{"y":1.000001,"x":0.5},{"y":1.00002,"x":0.525},{"y":1.0002012,"x":0.55},{"y":1.0012884,"x":0.575},{"y":1.005909,"x":0.6},{"y":1.0206947,"x":0.625},{"y":1.0576591,"x":0.65},{"y":1.131588,"x":0.675},{"y":1.2517223,"x":0.7},{"y":1.4119015,"x":0.725},{"y":1.5880985,"x":0.75},{"y":1.7482777,"x":0.775},{"y":1.868412,"x":0.8},{"y":1.9423409,"x":0.825},{"y":1.9793053,"x":0.85},{"y":1.994091,"x":0.875},{"y":1.9987116,"x":0.9},{"y":1.9997988,"x":0.925},{"y":1.99998,"x":0.95},{"y":1.999999,"x":0.975},{"y":2.0,"x":1.0},{"y":1.999999,"x":1.025},{"y":1.99998,"x":1.05},{"y":1.9997988,"x":1.075},{"y":1.9987116,"x":1.1},{"y":1.994091,"x":1.125},{"y":1.9793053,"x":1.15},{"y":1.9423409,"x":1.175},{"y":1.868412,"x":1.2},{"y":1.7482777,"x":1.225},{"y":1.5880985,"x":1.25},{"y":1.4119015,"x":1.275},{"y":1.2517223,"x":1.3},{"y":1.131588,"x":1.325},{"y":1.0576591,"x":1.35},{"y":1.0206947,"x":1.375},{"y":1.005909,"x":1.4},{"y":1.0012884,"x":1.425},{"y":1.0002012,"x":1.45},{"y":1.00002,"x":1.475},{"y":1.000001,"x":1.5},{"y":1.0,"x":1.525},{"y":1.0,"x":1.55},{"y":1.0,"x":1.575},{"y":1.0,"x":1.6},{"y":1.0,"x":1.625},{"y":1.0,"x":1.65},{"y":1.0,"x":1.675},{"y":1.0,"x":1.7},{"y":1.0,"x":1.725},{"y":1.0,"x":1.75},{"y":1.0,"x":1.775},{"y":1.0,"x":1.8},{"y":1.0,"x":1.825},{"y":1.0,"x":1.85},{"y":1.0,"x":1.875},{"y":1.0,"x":1.9},{"y":1.0,"x":1.925},{"y":1.0,"x":1.95},{"y":1.0,"x":1.975},{"y":1.0,"x":2.0}]}});</script></div>
```


$nx = 101$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.02},{"y":1.0,"x":0.04},{"y":1.0,"x":0.06},{"y":1.0,"x":0.08},{"y":1.0,"x":0.1},{"y":1.0,"x":0.12},{"y":1.0,"x":0.14},{"y":1.0,"x":0.16},{"y":1.0,"x":0.18},{"y":1.0,"x":0.2},{"y":1.0,"x":0.22},{"y":1.0,"x":0.24},{"y":1.0,"x":0.26},{"y":1.0,"x":0.28},{"y":1.0,"x":0.3},{"y":1.0,"x":0.32},{"y":1.0,"x":0.34},{"y":1.0,"x":0.36},{"y":1.0,"x":0.38},{"y":1.0,"x":0.4},{"y":1.0,"x":0.42},{"y":1.0,"x":0.44},{"y":1.0,"x":0.46},{"y":1.0,"x":0.48},{"y":1.000001,"x":0.5},{"y":1.00002,"x":0.52},{"y":1.0002012,"x":0.54},{"y":1.0012884,"x":0.56},{"y":1.005909,"x":0.58},{"y":1.0206947,"x":0.6},{"y":1.0576591,"x":0.62},{"y":1.131588,"x":0.64},{"y":1.2517223,"x":0.66},{"y":1.4119015,"x":0.68},{"y":1.5880985,"x":0.7},{"y":1.7482777,"x":0.72},{"y":1.868412,"x":0.74},{"y":1.9423409,"x":0.76},{"y":1.9793053,"x":0.78},{"y":1.994091,"x":0.8},{"y":1.9987116,"x":0.82},{"y":1.9997988,"x":0.84},{"y":1.99998,"x":0.86},{"y":1.999999,"x":0.88},{"y":2.0,"x":0.9},{"y":2.0,"x":0.92},{"y":2.0,"x":0.94},{"y":2.0,"x":0.96},{"y":2.0,"x":0.98},{"y":2.0,"x":1.0},{"y":1.999999,"x":1.02},{"y":1.99998,"x":1.04},{"y":1.9997988,"x":1.06},{"y":1.9987116,"x":1.08},{"y":1.994091,"x":1.1},{"y":1.9793053,"x":1.12},{"y":1.9423409,"x":1.14},{"y":1.868412,"x":1.16},{"y":1.7482777,"x":1.18},{"y":1.5880985,"x":1.2},{"y":1.4119015,"x":1.22},{"y":1.2517223,"x":1.24},{"y":1.131588,"x":1.26},{"y":1.0576591,"x":1.28},{"y":1.0206947,"x":1.3},{"y":1.005909,"x":1.32},{"y":1.0012884,"x":1.34},{"y":1.0002012,"x":1.36},{"y":1.00002,"x":1.38},{"y":1.000001,"x":1.4},{"y":1.0,"x":1.42},{"y":1.0,"x":1.44},{"y":1.0,"x":1.46},{"y":1.0,"x":1.48},{"y":1.0,"x":1.5},{"y":1.0,"x":1.52},{"y":1.0,"x":1.54},{"y":1.0,"x":1.56},{"y":1.0,"x":1.58},{"y":1.0,"x":1.6},{"y":1.0,"x":1.62},{"y":1.0,"x":1.64},{"y":1.0,"x":1.66},{"y":1.0,"x":1.68},{"y":1.0,"x":1.7},{"y":1.0,"x":1.72},{"y":1.0,"x":1.74},{"y":1.0,"x":1.76},{"y":1.0,"x":1.78},{"y":1.0,"x":1.8},{"y":1.0,"x":1.82},{"y":1.0,"x":1.84},{"y":1.0,"x":1.86},{"y":1.0,"x":1.88},{"y":1.0,"x":1.9},{"y":1.0,"x":1.92},{"y":1.0,"x":1.94},{"y":1.0,"x":1.96},{"y":1.0,"x":1.98},{"y":1.0,"x":2.0}]}});</script></div>
```


$nx = 121$


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"line","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":1.0,"x":0.0},{"y":1.0,"x":0.016666668},{"y":1.0,"x":0.033333335},{"y":1.0,"x":0.05},{"y":1.0,"x":0.06666667},{"y":1.0,"x":0.083333336},{"y":1.0,"x":0.1},{"y":1.0,"x":0.11666667},{"y":1.0,"x":0.13333334},{"y":1.0,"x":0.15},{"y":1.0,"x":0.16666667},{"y":1.0,"x":0.18333334},{"y":1.0,"x":0.2},{"y":1.0,"x":0.21666667},{"y":1.0,"x":0.23333333},{"y":1.0,"x":0.25},{"y":1.0,"x":0.26666668},{"y":1.0,"x":0.28333333},{"y":1.0,"x":0.3},{"y":1.0,"x":0.31666666},{"y":1.0,"x":0.33333334},{"y":1.0,"x":0.35},{"y":1.0,"x":0.36666667},{"y":1.0,"x":0.38333333},{"y":1.0,"x":0.4},{"y":1.0,"x":0.41666666},{"y":1.0,"x":0.43333334},{"y":1.0,"x":0.45},{"y":1.0,"x":0.46666667},{"y":1.0,"x":0.48333332},{"y":1.000001,"x":0.5},{"y":1.00002,"x":0.51666665},{"y":1.0002012,"x":0.53333336},{"y":1.0012884,"x":0.55},{"y":1.005909,"x":0.56666666},{"y":1.0206947,"x":0.5833333},{"y":1.0576591,"x":0.6},{"y":1.131588,"x":0.6166667},{"y":1.2517223,"x":0.6333333},{"y":1.4119015,"x":0.65},{"y":1.5880985,"x":0.6666667},{"y":1.7482777,"x":0.68333334},{"y":1.868412,"x":0.7},{"y":1.9423409,"x":0.71666664},{"y":1.9793053,"x":0.73333335},{"y":1.994091,"x":0.75},{"y":1.9987116,"x":0.76666665},{"y":1.9997988,"x":0.78333336},{"y":1.99998,"x":0.8},{"y":1.999999,"x":0.81666666},{"y":2.0,"x":0.8333333},{"y":2.0,"x":0.85},{"y":2.0,"x":0.8666667},{"y":2.0,"x":0.8833333},{"y":2.0,"x":0.9},{"y":2.0,"x":0.9166667},{"y":2.0,"x":0.93333334},{"y":2.0,"x":0.95},{"y":2.0,"x":0.96666664},{"y":2.0,"x":0.98333335},{"y":2.0,"x":1.0},{"y":1.999999,"x":1.0166667},{"y":1.99998,"x":1.0333333},{"y":1.9997988,"x":1.05},{"y":1.9987116,"x":1.0666667},{"y":1.994091,"x":1.0833334},{"y":1.9793053,"x":1.1},{"y":1.9423409,"x":1.1166667},{"y":1.868412,"x":1.1333333},{"y":1.7482777,"x":1.15},{"y":1.5880985,"x":1.1666666},{"y":1.4119015,"x":1.1833333},{"y":1.2517223,"x":1.2},{"y":1.131588,"x":1.2166667},{"y":1.0576591,"x":1.2333333},{"y":1.0206947,"x":1.25},{"y":1.005909,"x":1.2666667},{"y":1.0012884,"x":1.2833333},{"y":1.0002012,"x":1.3},{"y":1.00002,"x":1.3166667},{"y":1.000001,"x":1.3333334},{"y":1.0,"x":1.35},{"y":1.0,"x":1.3666667},{"y":1.0,"x":1.3833333},{"y":1.0,"x":1.4},{"y":1.0,"x":1.4166666},{"y":1.0,"x":1.4333333},{"y":1.0,"x":1.45},{"y":1.0,"x":1.4666667},{"y":1.0,"x":1.4833333},{"y":1.0,"x":1.5},{"y":1.0,"x":1.5166667},{"y":1.0,"x":1.5333333},{"y":1.0,"x":1.55},{"y":1.0,"x":1.5666667},{"y":1.0,"x":1.5833334},{"y":1.0,"x":1.6},{"y":1.0,"x":1.6166667},{"y":1.0,"x":1.6333333},{"y":1.0,"x":1.65},{"y":1.0,"x":1.6666666},{"y":1.0,"x":1.6833333},{"y":1.0,"x":1.7},{"y":1.0,"x":1.7166667},{"y":1.0,"x":1.7333333},{"y":1.0,"x":1.75},{"y":1.0,"x":1.7666667},{"y":1.0,"x":1.7833333},{"y":1.0,"x":1.8},{"y":1.0,"x":1.8166667},{"y":1.0,"x":1.8333334},{"y":1.0,"x":1.85},{"y":1.0,"x":1.8666667},{"y":1.0,"x":1.8833333},{"y":1.0,"x":1.9},{"y":1.0,"x":1.9166666},{"y":1.0,"x":1.9333333},{"y":1.0,"x":1.95},{"y":1.0,"x":1.9666667},{"y":1.0,"x":1.9833333},{"y":1.0,"x":2.0}]}});</script></div>
```


The results show with a grid size $nx$ increases, convection travels shorter distance.
With a given $nt = 20$ in the init param, the time windows becomes shorter as a result
of increasing $nx$.



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/scicloj/cfd-python-in-clojure/blob/main/notebooks/steps/cfl_condition.clj">notebooks/steps/cfl_condition.clj</a></small></small></pre></div>
```
