---
format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, notebooks/custom.scss]
    output-file: steps.step_04.html
code-block-background: true

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="steps.step_04_files/md-default0.js" type="text/javascript"></script><script src="steps.step_04_files/md-default1.js" type="text/javascript"></script><script src="steps.step_04_files/katex2.js" type="text/javascript"></script><script src="steps.step_04_files/vega3.js" type="text/javascript"></script><script src="steps.step_04_files/vega4.js" type="text/javascript"></script><script src="steps.step_04_files/vega5.js" type="text/javascript"></script><link href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css" rel="stylesheet" type="text/css" />

# 1-D Burgers' Equation
A fundamental PDE & convection-diffusion equation.

$$\frac{\partial u}{\partial t} + u \frac{\partial u}{\partial x} = \nu\frac{\partial^2 u}{\partial x^2}$$

Previously, convection eq'n:

$$\frac{\partial u}{\partial t} + u\frac{\partial u}{\partial x} = 0$$


and diffusion eq'n:

$$\frac{\partial u}{\partial t} = \nu\frac{\partial^2 u}{\partial x^2}$$


combining discretized equations from previous steps

$$\frac{u_i^{n+1} - u_i^n}{\Delta t} + u_i^n\frac{u_i^n - u_{i-1}^n}{\Delta x} = \nu\frac{u_{i+1}^n + u_{i-1}^n - 2u_i^n}{\Delta x^2}$$


rearranging the above results:

$$u_i^{n+1} = u_i^n - u_i^n \frac{\Delta t}{\Delta x}(u_i^n - u_{i-1}^n) + \nu\frac{\Delta t}{\Delta x^2}(u_{i+1}^n + u_{i-1}^n - 2u_i^n)$$


## Initials & Boundary Conditions


### Initial Conditions


$$u = -\frac{2\nu}{\phi}\frac{\partial \phi}{\partial x} + 4$$

$$\phi = \exp\bigg(\frac{-(x - 4t)^2}{4\nu(t + 1)}\bigg) + \exp\bigg(\frac{-(x - 4t - 2\pi)^2}{4\nu(t + 1)}\bigg)$$



### Boundary Condition


$$u(0) = u(2\pi)$$

This is called a _periodic boundary condition_.

Testing Burgers' Eqn:
_note_: currently not using adding equation very organically,
so we need to refactor.


::: {.sourceClojure}
```clojure
(one-d/burgers-u {:t 1.0 :x 4.0 :nu 3.0})
```
:::



::: {.printedClojure}
```clojure
3.4917066

```
:::


Working on generating lambdify-ed function:



::: {.sourceClojure}
```clojure
(def nx 101)
```
:::



::: {.sourceClojure}
```clojure
(def nt 100)
```
:::



::: {.sourceClojure}
```clojure
(def nu 0.07)
```
:::



::: {.sourceClojure}
```clojure
(def dx (* 2.0 PI (/ 1 (- nx 1))))
```
:::



::: {.sourceClojure}
```clojure
(def dt (* dx nu))
```
:::



::: {.sourceClojure}
```clojure
(def x-start 0)
```
:::



::: {.sourceClojure}
```clojure
(def x-end (* 2.0 PI))
```
:::



::: {.sourceClojure}
```clojure
(def init-params
  {:nx      nx
   :dx      dx
   :nt      nt
   :x-start x-start
   :x-end   x-end
   :nu      nu
   :dt      dt
   :mode    :burger})
```
:::


Calculate u and plot:


::: {.printedClojure}
```clojure
[3.982484, 4.0450406, 4.1075974, 4.170154, 4.232711, 4.2952676,
 4.3578243, 4.420381, 4.482938, 4.5454946, 4.6080513, 4.670608,
 4.733165, 4.7957215, 4.8582783, 4.920835, 4.983392, 5.045948,
 5.108505, 5.1710615, 5.2336183, 5.296175, 5.3587317, 5.4212885,
 5.483845, 5.546402, 5.6089587, 5.6715155, 5.734072, 5.796629,
 5.8591857, 5.9217424, 5.984299, 6.0468554, 6.109412, 6.171969,
 6.2345257, 6.2970824, 6.359639, 6.422196, 6.4847527, 6.5473094,
 6.609866, 6.672423, 6.734979, 6.797534, 6.860055, 6.9220233,
 6.9748416, 6.880349, 5.152262, 1.6489367, 1.0293779, 1.0453354,
 1.1050574, 1.1674429, 1.2299894, 1.2925454, 1.3551022, 1.4176589,
 1.4802157, 1.5427722, 1.6053289, 1.6678857, 1.7304426, 1.7929994,
 1.8555557, 1.9181124, 1.9806691, 2.0432258, 2.1057825, 2.1683393,
 2.230896, 2.2934527, 2.3560095, 2.4185662, 2.481123, 2.5436797,
 2.6062365, 2.6687932, 2.73135, 2.7939067, 2.8564634, 2.9190202,
 2.9815764, 3.0441332, 3.10669, 3.1692467, 3.2318034, 3.2943602,
 3.356917, 3.4194736, 3.4820304, 3.5445871, 3.6071439, 3.6697006,
 3.7322574, 3.794814, 3.8573709, 3.9199276, 3.9824843]

```
:::



```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"point","width":500,"height":300,"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"y","type":"quantitative"}},"data":{"values":[{"y":3.982484,"x":0.0},{"y":4.0450406,"x":0.06283186},{"y":4.1075974,"x":0.12566371},{"y":4.170154,"x":0.18849556},{"y":4.232711,"x":0.25132743},{"y":4.2952676,"x":0.31415927},{"y":4.3578243,"x":0.37699112},{"y":4.420381,"x":0.43982297},{"y":4.482938,"x":0.50265485},{"y":4.5454946,"x":0.56548667},{"y":4.6080513,"x":0.62831855},{"y":4.670608,"x":0.69115037},{"y":4.733165,"x":0.75398225},{"y":4.7957215,"x":0.81681406},{"y":4.8582783,"x":0.87964594},{"y":4.920835,"x":0.9424778},{"y":4.983392,"x":1.0053097},{"y":5.045948,"x":1.0681415},{"y":5.108505,"x":1.1309733},{"y":5.1710615,"x":1.1938052},{"y":5.2336183,"x":1.2566371},{"y":5.296175,"x":1.3194689},{"y":5.3587317,"x":1.3823007},{"y":5.4212885,"x":1.4451326},{"y":5.483845,"x":1.5079645},{"y":5.546402,"x":1.5707964},{"y":5.6089587,"x":1.6336281},{"y":5.6715155,"x":1.69646},{"y":5.734072,"x":1.7592919},{"y":5.796629,"x":1.8221238},{"y":5.8591857,"x":1.8849556},{"y":5.9217424,"x":1.9477874},{"y":5.984299,"x":2.0106194},{"y":6.0468554,"x":2.073451},{"y":6.109412,"x":2.136283},{"y":6.171969,"x":2.1991148},{"y":6.2345257,"x":2.2619467},{"y":6.2970824,"x":2.3247786},{"y":6.359639,"x":2.3876104},{"y":6.422196,"x":2.4504423},{"y":6.4847527,"x":2.5132742},{"y":6.5473094,"x":2.576106},{"y":6.609866,"x":2.6389377},{"y":6.672423,"x":2.7017696},{"y":6.734979,"x":2.7646015},{"y":6.797534,"x":2.8274333},{"y":6.860055,"x":2.8902652},{"y":6.9220233,"x":2.953097},{"y":6.9748416,"x":3.015929},{"y":6.880349,"x":3.0787609},{"y":5.152262,"x":3.1415927},{"y":1.6489367,"x":3.2044246},{"y":1.0293779,"x":3.2672563},{"y":1.0453354,"x":3.3300881},{"y":1.1050574,"x":3.39292},{"y":1.1674429,"x":3.455752},{"y":1.2299894,"x":3.5185838},{"y":1.2925454,"x":3.5814157},{"y":1.3551022,"x":3.6442475},{"y":1.4176589,"x":3.7070794},{"y":1.4802157,"x":3.7699113},{"y":1.5427722,"x":3.832743},{"y":1.6053289,"x":3.8955748},{"y":1.6678857,"x":3.9584067},{"y":1.7304426,"x":4.021239},{"y":1.7929994,"x":4.0840707},{"y":1.8555557,"x":4.146902},{"y":1.9181124,"x":4.209734},{"y":1.9806691,"x":4.272566},{"y":2.0432258,"x":4.3353977},{"y":2.1057825,"x":4.3982296},{"y":2.1683393,"x":4.4610615},{"y":2.230896,"x":4.5238934},{"y":2.2934527,"x":4.586725},{"y":2.3560095,"x":4.649557},{"y":2.4185662,"x":4.712389},{"y":2.481123,"x":4.775221},{"y":2.5436797,"x":4.8380527},{"y":2.6062365,"x":4.9008846},{"y":2.6687932,"x":4.9637165},{"y":2.73135,"x":5.0265484},{"y":2.7939067,"x":5.0893803},{"y":2.8564634,"x":5.152212},{"y":2.9190202,"x":5.215044},{"y":2.9815764,"x":5.2778754},{"y":3.0441332,"x":5.3407073},{"y":3.10669,"x":5.403539},{"y":3.1692467,"x":5.466371},{"y":3.2318034,"x":5.529203},{"y":3.2943602,"x":5.592035},{"y":3.356917,"x":5.6548667},{"y":3.4194736,"x":5.7176986},{"y":3.4820304,"x":5.7805305},{"y":3.5445871,"x":5.8433623},{"y":3.6071439,"x":5.906194},{"y":3.6697006,"x":5.969026},{"y":3.7322574,"x":6.031858},{"y":3.794814,"x":6.09469},{"y":3.8573709,"x":6.1575217},{"y":3.9199276,"x":6.2203536},{"y":3.9824843,"x":6.2831855}]}});</script></div>
```


^^_"saw-tooth function"_



## Periodic Boundary Conditions

With periodic boundary conditions, when a point gets to the right-hand side of the frame, it wraps around back to the front of the frame.

Bringing the discretized equation from the above:

$$u_i^{n+1} = u_i^n - u_i^n \frac{\Delta t}{\Delta x}(u_i^n - u_{i-1}^n) + \nu\frac{\Delta t}{\Delta x^2}(u_{i+1}^n + u_{i-1}^n - 2u_i^n)$$

Drawing both analytical and computational results in the same plot:


```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"mark":"point","width":500,"height":300,"layer":[{"mark":{"type":"line","color":"green","point":{"filled":false,"color":"green","fill":"white"}},"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"computational","type":"quantitative"}}},{"mark":{"type":"line","color":"orange"},"encoding":{"x":{"field":"x","type":"quantitative"},"y":{"field":"analytical","type":"quantitative"}}}],"data":{"values":[{"analytical":2.7781193,"computational":2.7665834,"x":0.0},{"analytical":2.8217578,"computational":2.810041,"x":0.06283186},{"analytical":2.8653965,"computational":2.8534985,"x":0.12566371},{"analytical":2.9090352,"computational":2.896956,"x":0.18849556},{"analytical":2.9526737,"computational":2.9404135,"x":0.25132743},{"analytical":2.9963124,"computational":2.9838707,"x":0.31415927},{"analytical":3.0399508,"computational":3.027328,"x":0.37699112},{"analytical":3.0835896,"computational":3.0707853,"x":0.43982297},{"analytical":3.127228,"computational":3.1142426,"x":0.50265485},{"analytical":3.1708667,"computational":3.1577,"x":0.56548667},{"analytical":3.2145052,"computational":3.2011576,"x":0.62831855},{"analytical":3.258144,"computational":3.244615,"x":0.69115037},{"analytical":3.3017824,"computational":3.2880726,"x":0.75398225},{"analytical":3.345421,"computational":3.33153,"x":0.81681406},{"analytical":3.3890595,"computational":3.3749874,"x":0.87964594},{"analytical":3.4326982,"computational":3.4184446,"x":0.9424778},{"analytical":3.476337,"computational":3.4619021,"x":1.0053097},{"analytical":3.5199754,"computational":3.5053596,"x":1.0681415},{"analytical":3.5636141,"computational":3.5488172,"x":1.1309733},{"analytical":3.6072526,"computational":3.5922744,"x":1.1938052},{"analytical":3.6508913,"computational":3.6357317,"x":1.2566371},{"analytical":3.6945298,"computational":3.679189,"x":1.3194689},{"analytical":3.7381685,"computational":3.7226465,"x":1.3823007},{"analytical":3.781807,"computational":3.766104,"x":1.4451326},{"analytical":3.8254457,"computational":3.8095615,"x":1.5079645},{"analytical":3.8690844,"computational":3.853019,"x":1.5707964},{"analytical":3.9127228,"computational":3.8964763,"x":1.6336281},{"analytical":3.9563613,"computational":3.9399338,"x":1.69646},{"analytical":4.0,"computational":3.983391,"x":1.7592919},{"analytical":4.0436387,"computational":4.0268483,"x":1.8221238},{"analytical":4.0872774,"computational":4.070306,"x":1.8849556},{"analytical":4.1309156,"computational":4.113763,"x":1.9477874},{"analytical":4.1745543,"computational":4.1572204,"x":2.0106194},{"analytical":4.218193,"computational":4.200678,"x":2.073451},{"analytical":4.2618313,"computational":4.2441354,"x":2.136283},{"analytical":4.30547,"computational":4.2875924,"x":2.1991148},{"analytical":4.3491087,"computational":4.33105,"x":2.2619467},{"analytical":4.3927474,"computational":4.3745074,"x":2.3247786},{"analytical":4.436386,"computational":4.417965,"x":2.3876104},{"analytical":4.480025,"computational":4.461422,"x":2.4504423},{"analytical":4.523663,"computational":4.5048795,"x":2.5132742},{"analytical":4.5673018,"computational":4.548337,"x":2.576106},{"analytical":4.6109405,"computational":4.5917945,"x":2.6389377},{"analytical":4.6545787,"computational":4.635252,"x":2.7017696},{"analytical":4.6982174,"computational":4.6787095,"x":2.7646015},{"analytical":4.741856,"computational":4.722167,"x":2.8274333},{"analytical":4.785495,"computational":4.765624,"x":2.8902652},{"analytical":4.8291335,"computational":4.8090816,"x":2.953097},{"analytical":4.8727717,"computational":4.852539,"x":3.015929},{"analytical":4.9164104,"computational":4.8959966,"x":3.0787609},{"analytical":4.960049,"computational":4.939454,"x":3.1415927},{"analytical":5.003688,"computational":4.982911,"x":3.2044246},{"analytical":5.047326,"computational":5.026369,"x":3.2672563},{"analytical":5.090965,"computational":5.0698266,"x":3.3300881},{"analytical":5.1346035,"computational":5.1132836,"x":3.39292},{"analytical":5.178242,"computational":5.1567407,"x":3.455752},{"analytical":5.221881,"computational":5.200197,"x":3.5185838},{"analytical":5.265519,"computational":5.2436533,"x":3.5814157},{"analytical":5.309158,"computational":5.2871075,"x":3.6442475},{"analytical":5.3527966,"computational":5.3305573,"x":3.7070794},{"analytical":5.3964353,"computational":5.3739967,"x":3.7699113},{"analytical":5.4400735,"computational":5.417413,"x":3.832743},{"analytical":5.483712,"computational":5.460777,"x":3.8955748},{"analytical":5.527351,"computational":5.5040193,"x":3.9584067},{"analytical":5.5709896,"computational":5.546986,"x":4.021239},{"analytical":5.6146283,"computational":5.5893273,"x":4.0840707},{"analytical":5.6582665,"computational":5.630253,"x":4.146902},{"analytical":5.7019053,"computational":5.667983,"x":4.209734},{"analytical":5.7455435,"computational":5.6985307,"x":4.272566},{"analytical":5.789182,"computational":5.7130485,"x":4.3353977},{"analytical":5.8328204,"computational":5.6922836,"x":4.3982296},{"analytical":5.876455,"computational":5.5961103,"x":4.4610615},{"analytical":5.920064,"computational":5.348928,"x":4.5238934},{"analytical":5.963493,"computational":4.8410926,"x":4.586725},{"analytical":6.0056477,"computational":4.01946,"x":4.649557},{"analytical":6.038797,"computational":3.0892584,"x":4.712389},{"analytical":6.0095024,"computational":2.4052658,"x":4.775221},{"analytical":5.5987864,"computational":2.0581272,"x":4.8380527},{"analytical":3.9999971,"computational":1.9277661,"x":4.9008846},{"analytical":2.401211,"computational":1.90015,"x":4.9637165},{"analytical":1.9904972,"computational":1.9154866,"x":5.0265484},{"analytical":1.961203,"computational":1.9479402,"x":5.0893803},{"analytical":1.9943523,"computational":1.9871031,"x":5.152212},{"analytical":2.0365071,"computational":2.028884,"x":5.215044},{"analytical":2.079936,"computational":2.0716863,"x":5.2778754},{"analytical":2.1235452,"computational":2.1148875,"x":5.3407073},{"analytical":2.1671796,"computational":2.1582446,"x":5.403539},{"analytical":2.2108176,"computational":2.2016628,"x":5.466371},{"analytical":2.254456,"computational":2.245105,"x":5.529203},{"analytical":2.2980947,"computational":2.2885563,"x":5.592035},{"analytical":2.3417332,"computational":2.3320115,"x":5.6548667},{"analytical":2.385372,"computational":2.375468,"x":5.7176986},{"analytical":2.4290106,"computational":2.418925,"x":5.7805305},{"analytical":2.472649,"computational":2.4623823,"x":5.8433623},{"analytical":2.5162878,"computational":2.5058396,"x":5.906194},{"analytical":2.5599263,"computational":2.5492969,"x":5.969026},{"analytical":2.603565,"computational":2.5927541,"x":6.031858},{"analytical":2.6472037,"computational":2.6362116,"x":6.09469},{"analytical":2.6908422,"computational":2.679669,"x":6.1575217},{"analytical":2.7344809,"computational":2.7231262,"x":6.2203536},{"analytical":2.7781193,"computational":2.7665834,"x":6.2831855}]}});</script></div>
```



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/scicloj/cfd-python-in-clojure/blob/main/notebooks/steps/step_04.clj">notebooks/steps/step_04.clj</a></small></small></pre></div>
```
